[package]
name = "rust_raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitcode = "1.1.2"
rand = "0.8.5"
libm = "0.2.2"
map_3d = "0.1.4"
configparser = "3.0.0"